#!/bin/bash
D=$(dirname "${BASH_SOURCE}")


# allow double-click launch of this script
if [[ -z "${TERM}" ]] || [[ "dumb" == "${TERM}" ]]; then
  # double clicked from linux desktop
  gnome-terminal -- "${BASH_SOURCE}"
  exit $?
fi


# determine a local IP interface reachable from a beacon server, in
# case launching from a multi-ip host, use of that IP can ensure that
# others can access the notebooks served here, from their desktops /
# laptops connected to the same network segment as the beacon server
BEACON_SERVER="dwcc.dw"
MYIP=$(
  python -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.connect(('${BEACON_SERVER}',80)); print(s.getsockname()[0])"
)


# set Python's adhoc search path to the workspace dir (i.e. parent dir)
WSD=$(
  python -c "import os; print(os.path.realpath('${D}/..'))"
)
export PYTHONPATH=${WSD}


# serve files only under this dir:
cd ${D}/Tour


# launch notebook server
jupyter notebook --ip="${MYIP}" --no-browser --NotebookApp.iopub_data_rate_limit=10000000000
